base_url = "https://kt.blog.ccmp.jp"
title = "ktaka's blog"
default_language = "ja"
compile_sass = false
build_search_index = false
generate_feeds = false

[languages.en]
generate_feeds = false
build_search_index = false

[markdown.highlighting]
enabled = true
theme = "github-dark"
