base_url = "https://ktaka.blog.ccmp.jp"
title = "ktaka's blog"
default_language = "ja"
compile_sass = false
build_search_index = false
generate_feeds = true

[languages.en]
generate_feeds = true
build_search_index = false

[markdown.highlighting]
enabled = true
theme = "github-dark"
